config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'game#index'
  get 'game/start' => 'game#start', :as => 'start'
  get 'game/rank' => 'game#rank', :as => 'rank'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/sight.rb
class Sight < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_action :authenticate_user!
  def index; end

  def start
    @image = rand(1..10)
  end

  def rank

  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/game/index.html.erb
<div class="input-form">
    <%= form_tag(start_path, :method => "get", class: "start-game") do %>
    <%= submit_tag("Play", class: "start-button")%>
    <% end %>
    <%= form_tag(rank_path, :method => "get") do %>
    <%= submit_tag("Top", class: "rank") %>
    <% end %>
</div>

app/views/game/rank.html.erb
<div>
   Здесь будет рейтинг
</div>

app/views/game/start.html.erb
<body>
<h2><%= "Where is this?" %></h2>
<%= image_tag ('/assets/' + @image.to_s + '.png'), class: 'image'%>
<div id="map" style="width: 100%; height: 600px"></div>
<%= form_tag(root_path, :method => "get") do %>
  <%= submit_tag("Guess", class: 'guess-button') %>
<%end %>
<script type="text/javascript">
    var marker = null;
    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 4,
            center: {lat: 25.363882, lng: 131.044922 }
        });
        map.addListener('click', function(e) {
            if (marker != null)
                marker.setMap(null);
            placeMarkerAndPanTo(e.latLng, map);
        });
    }
    function placeMarkerAndPanTo(latLng, map) {
        marker = new google.maps.Marker({
            position: latLng,
            map: map
        });
        map.panTo(latLng);
        var latcor = marker.getPosition().lat();
        var lngcor = marker.getPosition().lng();
        jQuery.ajax({
            data: {'lat':  latcor, 'lng': lngcor},
            dataType: 'script',
            type: 'get',
            url: "/game/getcoordinate",
        });
    }
</script>
</body>
<script async defer src="https://maps.googleapis.com/maps/api/js?libraries=places&key=[your_key]&callback=initMap"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SightFindProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if user_signed_in? %>
  <span><%="hello" %><%= current_user.username %></span>
  <%= link_to "exit", destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to "enter", new_user_session_path %> или <%= link_to "register", new_user_registration_path %>
<% end %>
  <body>
    <%= yield %>
  </body>
</html>